<?php
/**
 * This file is part of the Nella Framework.
 *
 * Copyright (c) 2006, 2011 Patrik Votoček (http://patrik.votocek.cz)
 *
 * This source file is subject to the GNU Lesser General Public License. For more information please see http://nella-project.org
 */
?>
<style>
#nella-debug-content table {
	width: 100%;
}
#nella-debug-content h2 {
	font-weight: bold;
	font-size: 1.2em;
}
</style>

<h1>Debug</h1>

<div class="nette-inner" id="nella-debug-content">
	<h2>Services</h2>
	<table>
		<tr>
			<th>Name</th>
			<th>Class / Type</th>
		</tr>
		<?php $i = 0; foreach ($services as $service): ?>
		<tr>
			<td><?php echo htmlspecialchars($service['name']) ?></td>
			<td>
				<?php echo htmlspecialchars($service['type']) ?> <?php if($service['instance']): ?><a href="#" rel="#nella-debug-content-service-<?php echo $i ?>">dump</a>
				<div class="nette-collapsed" id="nella-debug-content-service-<?php echo $i ?>">
					<?php echo \Nette\Diagnostics\Helpers::clickableDump($service['instance']); $i++; ?>
				</div>
				<?php endif ?>
			</td>
		</tr>
		<?php endforeach ?>
	</table>
	<?php if (count($templates)): ?>
	<h2>Templates</h2>
	<table style="width: 100%">
		<?php $i = 0; foreach ($templates as $control => $paths): ?>
		<tr>
			<th><?php echo htmlspecialchars($control) ?> <a href="#" rel="#nella-debug-content-template-<?php echo $i ?>">dump</a></th>
		</tr>
		<tr class="nette-collapsed" id="nella-debug-content-template-<?php echo $i ?>">
			<td><?php echo \Nette\Diagnostics\Helpers::clickableDump($paths) ?></td>
		</tr>
		<?php endforeach ?>
	</table>
	<?php endif ?>
</div>