<?php
/**
 * This file is part of the Nella Framework.
 *
 * Copyright (c) 2006, 2011 Patrik Votoček (http://patrik.votocek.cz)
 *
 * This source file is subject to the GNU Lesser General Public License. For more information please see http://nella-project.org
 */

namespace Nella\Panels;
?>
<h1>Libraries Versions</h1>

<div class="nette-inner nette-addons-VersionPannel">
	<table>
	<tr>
		<th>PHP</th>
		<td><?php echo PHP_VERSION ?></td>
		<td><?php echo PHP_OS." ".(defined('PHP_SAPI') ? (PHP_SAPI." ") : NULL ).php_uname('m'); if (extension_loaded('xdebug')): ?> (Xdebug <?php echo phpversion('xdebug') ?>)<?php endif ?></td>
	</tr>
	<?php if (isset($_SERVER['SERVER_SOFTWARE'])): ?>
	<tr>
		<th>Server</th>
		<td colspan="2"><?php echo $_SERVER['SERVER_SOFTWARE'] ?></td>
	</tr>
	<?php endif ?>
	<?php foreach ($libs as $lib): ?>
	<tr>
		<th><?php echo htmlspecialchars($lib['name']) ?></th>
		<td<?php if (!isset($lib['revision'])): ?> colspan="2"<?php endif ?>><?php echo htmlspecialchars($lib['version']) ?></td>
		<?php if (isset($lib['revision'])): ?><td><?php echo htmlspecialchars($lib['revision']) ?></td><?php endif ?>
	</tr>
	<?php endforeach ?>
	</table>
	<?php if (isset($updates) && count($updates) > 0): ?>
	<h2>Updates avaiable</h2>
	<table>
	<?php foreach($updates as $name => $update): ?>
	<tr>
		<th><?php echo $name ?></th>
		<td><?php echo $update['version'] ?></td>
		<td><?php echo $update['revision'] ?></td>
		<td>
			<?php if (isset($update['url'])): ?>
			<a href="<?php echo $update['url'] ?>" target="_blank">Download</a>
			<?php else: ?>
			&nbsp;
			<?php endif ?>
		</td>
	</tr>
	<?php endforeach ?>
	</table>
	<?php endif ?>
</div>
