<?php
/**
 * This file is part of the Nella Framework (http://nellafw.org).
 *
 * Copyright (c) 2006, 2012 Patrik Votoček (http://patrik.votocek.cz)
 *
 * For the full copyright and license information,
 * please view the file LICENSE.txt that was distributed with this source code.
 */

namespace Nella\Templating\Diagnostics;

use Nette\Diagnostics\Helpers;

?>
<style>#nette-debug .nella-TemplateFilesPanel .nette-inner{width:700px}#nette-debug .nette-ContainerPanel table{width:100%;white-space:nowrap}#nette-debug .nette-ContainerPanel-parameters pre{background:#FDF5CE;padding:.4em .7em;border:1px dotted silver;overflow:auto}#nette-debug .nette-ContainerPanel .created{font-weight:bold}#nette-debug .nella-TemplateFilesPanel .yes{color:green;font-weight:bold}</style>

<div class="nella-TemplateFilesPanel">
	<h1>Template Files</h1>

	<div class="nette-inner">
		<?php foreach ($files as $input => $list): ?>
		<h2><a href='#' class='nette-toggler' rel='#nette-TemplateFilesPanel-row-<?php echo md5($input); ?>'><?php echo htmlspecialchars($input); ?></a></h2>

		<div id='nette-TemplateFilesPanel-row-<?php echo md5($input); ?>' class='nette-collapsed'>
			<?php echo nl2br(htmlspecialchars(implode(" \n", $list))); ?>
		</div>
		<?php endforeach ?>
	</div>
</div>

