<?php
/**
 * This file is part of the Nella Framework.
 *
 * Copyright (c) 2006, 2011 Patrik Votoček (http://patrik.votocek.cz)
 *
 * This source file is subject to the GNU Lesser General Public License. For more information please see http://nella-project.org
 */
?>
<h1>Translations for '<?php echo htmlspecialchars($lang) ?>'</h1>

<div class="nette-inner" id="nella-translator-panel-content">
	<p id="nella-translator-panel-notloaded">Data not loaded</p>
	<div id="nella-translator-panel-content-inner">
		<div id="nella-translator-panel-content-dictionary">
			<select id="nella-translator-panel-content-dictionaries-list"></select>
			<input type="text" class="text" id="nella-translator-panel-content-dictionaries-pluralform">
		</div>
		<div id="nella-translator-panel-content-sidebar">
			<!--<input type="text" class="text" id="nella-translator-panel-content-dictionaries-filter">
			<div id="nella-translator-panel-content-dictionaries-filter-reset"></div>-->
			<div id="nella-translator-panel-content-dictionary-translations">
				<p id="nella-translator-panel-forms-translations-empty">Empty</p>
			</div>
		</div>
		<div id="nella-translator-panel-content-editor">
			<p id="nella-translator-panel-content-forms-notset">Data not loaded (maybe missing jQuery)</p>
		</div>
		<br style="clear: both;">
		<div id="nella-translator-panel-content-actions">
			<input type="button" class="button" value="Reload" id="nella-translator-panel-content-actions-relaod">
			<input type="button" class="button" value="Extract" id="nella-translator-panel-content-actions-extract">
			<input type="button" class="button" value="Save" id="nella-translator-panel-content-actions-save">
		</div>
	</div>
</div>

<style>
	#nella-translator-panel-content {
		width: 460px;
	}
	#nella-translator-panel-content-inner {
		display: none;
	}

	#nella-translator-panel-content-dictionaries-list {
		width: 150px;
		border: 1px solid #ccc;
	}
	#nella-translator-panel-content-sidebar{
		margin: 0;
		padding: 0;
		width: 150px;
		float: left;
		border: 1px solid #eee;
		max-height: 400px;
		overflow: auto;
	}

	#nella-translator-panel-content-dictionary-translations span {
		display: block;
		border: 1px solid #ccc;
		padding: 2px;
		margin: 1px;
	}

	#nella-translator-panel-content-dictionary-translations span.saved {
		background-color: #efe;
	}

	#nella-translator-panel-content-dictionary-translations span.unsaved {
		background-color: #ffe;
	}

	#nella-translator-panel-content-dictionary-translations span.untranslated {
		background-color: #fee;
	}

	#nella-translator-panel-content-dictionaries-pluralform {
		width: 300px;
		border: 1px solid #ccc;
	}
	#nella-translator-panel-content-editor {
		margin: 5px;
		padding: 5px;
		width: 280px;
		float: right;
		overflow: auto;
	}
	#nella-translator-panel-content-editor textarea {
		width: 100%;
		display: block;
		margin-bottom: 5px;
		border: 1px solid #ccc;
	}
	#nella-translator-panel-content-actions {
		text-align: right;
	}
	#nella-translator-panel-content-actions input {
		background-color: #eee;
		padding: 2px;
	}
</style>

<script>
var Nella = Nella || {};

Nella.translator = {};

Nella.translator.forms = function(pluralForm) {
	var pos = pluralForm.indexOf('=') + 1;
	return pluralForm.substr(pos, pluralForm.indexOf(';') - pos);
};

Nella.translator.data = eval(<?php echo \Nette\Utils\Json::encode($dictionaries) ?>);
Nella.translator.lang = "<?php echo $lang ?>";

Nella.translator.renderDictionaryList = function(dictionaries) {
	var $list = $('#nella-translator-panel-content-dictionaries-list');
	$list.html($('<option>').attr('value', 0).text('Select dictionary'));
	for (var i in dictionaries) {
		var $dictionary = $('<option>').attr('value', i).text(dictionaries[i]['name']);
		$dictionary.click(function() {
			var $this = $(this);
			Nella.translator.loadDictionary($this.attr('value'));
		});
		$list.append($dictionary);
	}
};

Nella.translator.renderPluralForm = function(pluralForm) {
	var $input = $('#nella-translator-panel-content-dictionaries-pluralform');
	$input.attr('disabled', false).val(pluralForm);
};

Nella.translator.renderTranslationsList = function(translations) {
	var $list = $('#nella-translator-panel-content-dictionary-translations');
	$list.html(null);
	for (var i in translations) {
		var $translation = $('<span>').text(i);
		if (translations[i]['status'] == true) {
			$translation.addClass('saved');
		} else if (translations[i]['status'] == false) {
			$translation.addClass('unsaved');
		} else {
			$translation.addClass('untranslated');
		}

		$translation.click(function() {
			var dictionary = Nella.translator.getActiveDictionary();
			if (!Nella.translator.data[dictionary]['pluralForm']) {
				Nella.translator.data[dictionary]['pluralForm'] = $('#nella-translator-panel-content-dictionaries-pluralform').val();
				if (!Nella.translator.data[dictionary]['pluralForm'] || !Nella.translator.data[dictionary]['pluralForm'].indexOf('nplurals')) {
					alert("Please first set valid plural forms");
					$('#nella-translator-panel-content-dictionaries-pluralform')[0].focus();
					return false;
				}
			}
			var forms = Nella.translator.forms(Nella.translator.data[dictionary]['pluralForm']);
			Nella.translator.renderEditor($(this).text(), forms, translations[$(this).text()]['translation']);
		});

		$list.append($translation);
	}
};

Nella.translator.renderEditor = function(message, forms, translations) {
	var $editor = $('#nella-translator-panel-content-editor');
	$editor.html(null);
	for (var i = 0; i < forms; i++) {
		var text = "";
		if (translations[i]) {
			text = translations[i];
		}
		$editor.append($('<textarea>').text(text).attr('data-nella-translator-message', message).attr('data-nella-translator-form', i).change(function() {
			var activeDictionary = Nella.translator.getActiveDictionary();
			if (activeDictionary) {
				var $this = $(this);
				Nella.translator.data[activeDictionary]['translations'][$this.attr('data-nella-translator-message')]['translation'][$this.attr('data-nella-translator-form')] = $this.val();
				Nella.translator.data[activeDictionary]['translations'][$this.attr('data-nella-translator-message')]['status'] = false;
				Nella.translator.renderTranslationsList(Nella.translator.data[activeDictionary]['translations']);
			}
		}));
	}
};

Nella.translator.loadDictionary = function(dictionary) {
	if (!Nella.translator.data[dictionary]['pluralForm']) {
		Nella.translator.data[dictionary]['pluralForm'] = $('#nella-translator-panel-content-dictionaries-pluralform').val();
	}
	var data = Nella.translator.data[dictionary];
	Nella.translator.renderPluralForm(data['pluralForm']);
	Nella.translator.renderTranslationsList(data['translations'])
};

Nella.translator.getActiveDictionary = function() {
	return $('#nella-translator-panel-content-dictionaries-list').val();
};

Nella.translator.renderProcessing = function() {
	$('#nella-translator-panel-content-editor').html(
		$('<p id="nella-translator-panel-content-forms-notset">Please select dictionary</p>')
	);

	$('#nella-translator-panel-content-dictionary-translations').html(
		$('<p id="nella-translator-panel-forms-translations-empty">Empty</p>')
	);
	$('#nella-translator-panel-content-dictionaries-list').val(0);
};

if (!!window.jQuery) {
$(document).ready(function() {
	$('#nella-translator-panel-content-forms-notset').html("Data not loaded");
	//Nella.translator.renderPluralForm();
	$('#nella-translator-panel-content-dictionaries-list').change(function() {
		var $this = $(this);
		if ($this.val() != 0) {
			Nella.translator.loadDictionary($this.val());
		}
	});

	$('#nella-translator-panel-content-dictionaries-pluralform').change(function() {
		var activeDictionary = Nella.translator.getActiveDictionary();
		if (activeDictionary) {
			Nella.translator.data[activeDictionary]['pluralForm'] = $(this).val();
		}
	});

	Nella.translator.renderDictionaryList(Nella.translator.data);
	$('#nella-translator-panel-content-inner').show();
	$('#nella-translator-panel-content-editor').html(
		$('<p id="nella-translator-panel-content-forms-notset">Please select dictionary</p>')
	);
	$('#nella-translator-panel-notloaded').hide();

	$('#nella-translator-panel-content-actions-relaod').click(function() {
		Nella.translator.renderProcessing();
		jQuery.ajax({
			type: 'POST',
			url: window.location.href,
			data: {action: "get", lang: Nella.translator.lang},
			beforeSend: function(jqXHR) {
				jqXHR.setRequestHeader('<?php echo self::XHR_HEADER ?>', 'true');
			},
			success: function(data) {
				Nella.translator.data = data.data;
			}
		});
		return false;
	});

	$('#nella-translator-panel-content-actions-extract').click(function() {
		Nella.translator.renderProcessing();
		jQuery.ajax({
			type: 'POST',
			url: window.location.href,
			data: {action: "extract", lang: Nella.translator.lang},
			beforeSend: function(jqXHR) {
				jqXHR.setRequestHeader('<?php echo self::XHR_HEADER ?>', 'true');
			},
			success: function(data) {
				Nella.translator.data = data.data;
			}
		});
		return false;
	});

	$('#nella-translator-panel-content-actions-save').click(function() {
		Nella.translator.renderProcessing();
		jQuery.ajax({
			type: 'POST',
			url: window.location.href,
			data: {action: "save", lang: Nella.translator.lang, data: Nella.translator.data},
			beforeSend: function(jqXHR) {
				jqXHR.setRequestHeader('<?php echo self::XHR_HEADER ?>', 'true');
			},
			success: function(data) {
				Nella.translator.data = data.data;
			}
		});
		return false;
	});
});
}
</script>
